Improve legate wheel download error checking (#967)
Improve error checking if the run ID is not found for the legate wheel from the SHA. Add some improvements to the search query as well. This was failing in a surprising way where no run found resulted in an empty string which the `gh` CLI didn't error on, but instead consumed all API calls for the user over time.

diff --git a/continuous_integration/scripts/tools/legate-gh-download-artifact b/continuous_integration/scripts/tools/legate-gh-download-artifact
--- a/continuous_integration/scripts/tools/legate-gh-download-artifact
+++ b/continuous_integration/scripts/tools/legate-gh-download-artifact
@@ -26,6 +26,11 @@ output_path="${3}"
 
 echo "Downloading and decompressing artifact ${artifact_name} from run ${run_id} to ${output_path}"
 
+if [[ -z "${run_id}" ]]; then
+  echo "Error no run ID was found for the given SHA."
+  exit 1
+fi
+
 gh run download "${run_id}" \
   --repo "${LEGATE_REPO_NAME}" \
   --name "${artifact_name}" \
